import type { Metadata } from "next";
import "./globals.css";
import { Web3Modal } from "./contexts/web3Modal";
import { WrappedToastContainer } from "./components/Toast";
import { Navbar } from "./components/layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Web3Modal>
      <WrappedToastContainer />
      <Navbar />
      {children}
    </Web3Modal>
  );
}
